config/routes.rb
ApiMock::Application.routes.draw do
  
  resources :charities do
    resources :reviews
  end

  match 'charities/id/:id' => 'charities#show'

  root :to => 'charities#index'

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  attr_accessible :country, :description, :location, :name
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :author, :charity_id, :description, :name, :rating, :recommend, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
    @charities_list = @charities.map{|c| c.id}

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json {
        render json: {"charities" => @charities_list}
    #  }
    #end
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
    @charity = Charity.find(params[:id])

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json {
        render json: @charity
    #  }
    #end
  end

  # GET /charities/new
  # GET /charities/new.json
  def new
    @charity = Charity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charity }
    end
  end

  # GET /charities/1/edit
  def edit
    @charity = Charity.find(params[:id])
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(params[:charity])

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render json: @charity, status: :created, location: @charity }
      else
        format.html { render action: "new" }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charities/1
  # PUT /charities/1.json
  def update
    @charity = Charity.find(params[:id])

    respond_to do |format|
      if @charity.update_attributes(params[:charity])
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity = Charity.find(params[:id])
    @charity.destroy

    respond_to do |format|
      format.html { redirect_to charities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json

  def index
    @reviews = Review.all
    @reviews_list = @reviews.map{|r| r.id}

    #respond_to do |format|
     # format.html # index.html.erb
      #format.json { render json: @reviews }
      render json: {"reviews" => @reviews_list}
    #end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    #respond_to do |format|
     # format.html # show.html.erb
      #format.json { render json: @review }
      @temp = {
        "charity-id" => @review.charity_id,
        "author" => @review.author,
        "title" => @review.title,
        "description" => @review.description,
        "name" => @review.name,
        "rating" => @review.rating,
        "statements" => [1,1,1,1,1,1,1,1,1,1],
        "orientation" => 1,
        "liked-best" => [1,1,0,1,1,1,1,1,1,1,1,1,0,1,0],
        "liked-best-other" => "",
        "liked-least" => [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
        "liked-least-other" => "",
        "suggestions" => "More funding needed to help build the charity",
        "why" => [1,0,0,0,0,0,0,1,1],
        "why-other"=>"",
        "goals"=>1,
        "comments"=>["author"=>@review.author, "comment"=>"We're glad you had a great time"]
      }
      render json: @temp
    #end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/charity_helper.rb
module CharityHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<h1>Listing charities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Country</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @charities.each do |charity| %>
  <tr>
    <td><%= charity.name %></td>
    <td><%= charity.location %></td>
    <td><%= charity.country %></td>
    <td><%= charity.description %></td>
    <td><%= link_to 'Show', charity %></td>
    <td><%= link_to 'Edit', edit_charity_path(charity) %></td>
    <td><%= link_to 'Destroy', charity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Charity', new_charity_path %>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @charity.name %>
</p>

<p>
  <b>Location:</b>
  <%= @charity.location %>
</p>

<p>
  <b>Country:</b>
  <%= @charity.country %>
</p>

<p>
  <b>Description:</b>
  <%= @charity.description %>
</p>


<%= link_to 'Edit', edit_charity_path(@charity) %> |
<%= link_to 'Back', charities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiMock</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :charity_id %><br />
    <%= f.text_field :charity_id %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :recommend %><br />
    <%= f.check_box :recommend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Charity-id</th>
    <th>Author</th>
    <th>Title</th>
    <th>Description</th>
    <th>Name</th>
    <th>Rating</th>
    <th>Recommend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.charity_id %></td>
    <td><%= review.author %></td>
    <td><%= review.title %></td>
    <td><%= review.description %></td>
    <td><%= review.name %></td>
    <td><%= review.rating %></td>
    <td><%= review.recommend %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Charity_id:</b>
  <%= @review.charity_id %>
</p>

<p>
  <b>Author:</b>
  <%= @review.author %>
</p>

<p>
  <b>Title:</b>
  <%= @review.title %>
</p>

<p>
  <b>Description:</b>
  <%= @review.description %>
</p>

<p>
  <b>Name:</b>
  <%= @review.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Recommend:</b>
  <%= @review.recommend %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>